#!/usr/bin/env node

const Promise = require("bluebird");
const Sugar = require("sugar");
const _progress = require('cli-progress');

Sugar.extend();
const modifyExtPaths = require('./modules/modifyExtPaths');
const lowercase = require('./modules/lowercase');
let globalResults = require('./modules/discoveries.js');
let globalBar;

const log = console.log;

let httpz;
try {
  httpz = require("./modules/httpz")
} catch (err) {

}

var argv = require("yargs").argv,
  genCustomBackupFiles = require('./modules/customBackupFiles'),
  pathsToCheck = [],
  color = require("cli-color"),
  async = require("async"),
  fs = require("fs"),
  throttledQueue = require("throttled-queue"),
  Table = require('cli-table'),
  table = new Table(),
  totalChecks = 0,
  checkCounter = 0,
  rate = 15,
  lastPercent = 0,
  testResults = [];

(testString = ""),
  (debug = false),
  (jobs = 0),
  (jobsCount = 0),
  (test = false),
  (count = 0),
  (wordDir = require.resolve("cli-color"));

wordDir = wordDir.split("node_modules");
wordDir = wordDir[0];

var dictionaryFile = wordDir + "wordlists/default.txt";
if (argv.input || argv.wordlist) {
  if (argv.input) {
    dictionaryFile = argv.input;
  } else {
    dictionaryFile = argv.wordlist;
  }
}

if (argv.rate) {
  rate = parseInt(argv.rate);
}


async function asyncForEach(array, callback) {
  for (let index = 0; index < array.length; index++) {
    await callback(array[index], index, array)
  }
}

async function prepPaths(payloadArray) {
  if (argv.help || argv.h || !argv.u) {
    console.log(color.green("\n--[Dirp Examples]--\n"));
    console.log("./dirp -u 'https://foo.bar/' --wordlist=/path/to/wordlist.txt");
    console.log("./dirp -u 'https://foo.bar/<INSERT>.jsp'");
    console.log(
      "./dirp -u 'https://foo.bar/' --cookie='sessionid=12345;foo=bar;'"
    );
    console.log("./dirp -u 'https://foo.bar/' --proxy='http://proxy.host:port'");
    console.log("           '--rate 50 (max number of requests per second - default 15)");
    console.log("           '--lowercase (lowercase all paths)");
    console.log("           '--ext .php (Replace any extensions with user defined value)");
    console.log("           '--debug (debug mode and show every request/response)");

    console.log();
    process.exit(1);
  } else if (argv.u) {

    if (argv.string) {
      testString = argv.string;
    }

    if (argv.debug) {
      debug = true;
    }


    let customBackups = genCustomBackupFiles(argv.u.split('/')[2]);


    if (argv.ext) {
      payloadArray = await modifyExtPaths(payloadArray, argv.ext);
    }

    if (argv.lowercase) {
      payloadArray = await lowercase(payloadArray);
    }


    totalChecks = payloadArray.length;

    const jobCount = payloadArray.length

    console.log(
      "\n[*] Using wordlist which contains %s checks\n",
      payloadArray.length
    );


    return payloadArray

  }


}

async function dirpPath(checks, recurse, clibar) {
  let bar;
  if (typeof (recurse) != 'String') {
    bar = recurse;
    recurse = false;
  } else {
    bar = clibar;
  }

  if (!argv.debug) {
    bar.start(checks.length, 1);


    bar.update(0, {
      reqPath: '...',
      discoveries: '',
    });
  }


  return Promise.map(checks, function (pay) {
    if (recurse) {
      pay = `${recurse}/${pay}`;
    }

    return new Promise(function (resolve) {
      resolve(httpz(argv.u, testString, debug, pay, bar))
    })

  }, { concurrency: rate })

}


function cleanResults(rawRes) {
  return rawRes.filter(function (el) {
    return el != null;
  });
}


(async function () {
  let data;
  let payloadArray;
  try {
    data = fs.readFileSync(dictionaryFile, "utf8");
    payloadArray = data.toString().split("\n");
  } catch (e) {

  }

  let e = await prepPaths(payloadArray);

  let bar = new _progress.Bar({
    format: '{bar} {percentage}% ' + '| ETA: {eta}s | {value}/{total} | Discovered: {discoveries} ',
    barCompleteChar: '\u2588',
    forceRedraw: true,
    barIncompleteChar: '\u2591',
    hideCursor: true
  });
  globalBar = bar;
  let results = await dirpPath(e, bar);
  var filtered = cleanResults(results);

  await asyncForEach(filtered, async (result) => {
    if (!result.path.includes('//') && result.path != '/' && result.path.length > 2) {
      pathsToCheck.push(result.path);
    }
  })

  if (argv.recurse || argv.r || argv.recursive) {
    await asyncForEach(pathsToCheck, async (num) => {

      let results = await dirpPath(e, num, bar);
      var filtered = cleanResults(results);
      for (i = 0; i < filtered.length; i++) {
        if (!filtered[i].path.includes('//') && filtered[i].path.length > 2) {
          pathsToCheck.push(filtered[i].path)
        }
      }

    })
  } else {
    if (!argv.debug) {
      bar.stop();
    }

  }




})()


function drawTable() {
  var resultsTable = new Table({
    head: ['Method', 'Url', 'Length', 'Status'],
    style: { compact: true, 'padding-left': 1 }
  });
  let finalDiscoveries = globalResults.getDiscoveries();
  for (i = 0; i < finalDiscoveries.length; i++) {
    let resStrSplit = finalDiscoveries[i].split(" ");
    resultsTable.push(
      [resStrSplit[0], resStrSplit[1], resStrSplit[2], resStrSplit[3]]
    );
  }
  console.log(resultsTable.toString());
}
let hasPrintedResults = false;
function handle(signal) {

  globalBar.stop();
  if (signal === "SIGINT") {
    console.log(globalResults.getDiscoveries().join("\n"))
    hasPrintedResults = true;
  } else {
    if (!hasPrintedResults) {
      drawTable();
      hasPrintedResults = true;
    }
  }

  process.exit(0);
}

process.on('SIGINT', handle);
process.on('SIGINT', handle);
process.on('SIGTERM', handle);
process.on('exit', function () {

  handle();


  //console.log(http.discoveries.length + " matches found\n");

  // table.push(
  //     { 'Some key': 'Some value' }
  //   , { 'Another key': 'Another value' }
  // );

  // console.log(resultsTable.toString());
});

